# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the master branch
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     - name: Install Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: '10.x'
#     - name: Deploy to Server
#       uses: easingthemes/ssh-deploy@v2.0.7
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#         SOURCE: "dist/"
#         REMOTE_HOST: '119.29.101.122'
#         REMOTE_USER: 'root'
#         TARGET: '/test'

name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      # - name: SSH Auto Deploy
      #   uses: hengkx/ssh-deploy@v1.0.1
      #   env:
      #     HOST: 119.29.101.122
      #     USERNAME: root
      #     PASSWORD: ${{secrets.PASSWORD}}
      #     SOURCE: './'
      #     TARGET: /test
      #     AFTER_COMMAND: './install.ssh'
      # - name: Rsync Deployments Action
      #   uses: Burnett01/rsync-deployments@4.1
      #   with:
      #     path: ./
      #     remote_path: /test
      #     remote_host: 119.29.101.122
      #     remote_user: root
      #     remote_key: ${{ secrets.SERVER_SSH_KEY }}
          # rsh: -l root 119.29.101.122 /test/install.sh
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./"
          REMOTE_HOST: "119.29.101.122"
          REMOTE_USER: "root"
          TARGET: "/test"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: root@119.29.101.122
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          command: |
            cd /test
            cnpm install
            cnpm run start
